### ISSUE TITLE
Add support for Google LLMs

### ISSUE THREAD

**Issue by andreibondarev** [andreibondarev/langchainrb#38]

**Comment by ZhenhangTung** [comment]
Can't wait for this feature! I cannot upgrade to OpenAI's pro plan due to payment method issues. So now I either choose a different LLM like Google's Bard, or buy API keys from individuals. The later one would have security issue and not appropriate for production env.

**Comment by andreibondarev** [comment]
@ZhenhangTung Cool, I'm going to work on it.

**Comment by ZhenhangTung** [comment]
Thanks! I'll try to find if there is anything I can help with. I am frustrated by Python's dominance in the field of AI. I believe with LLM, the bar of starting a tech startup is lower than previous decade. If anyone choose Rails to build their product and find himself have to build another service written in Python, that would be annoying. And it could slow down the development speed? Instead of building a monolith application, we are building micro-services.

**Comment by andreibondarev** [comment]
@ZhenhangTung Please test out the new support Google PaLM LLM.

As you use langchainrb, I would love to get any feedback you might have, good or bad! Thank you!
