### ISSUE TITLE
typeerror with chain_of_thought_agent 

### ISSUE THREAD

**Issue by pargara** [andreibondarev/langchainrb#82]
When I run the following code I get this error 

```ruby

require "langchain"
require 'google_search_results'


GoogleSearch.api_key = ENV[KEY_SERAPI]


agent = Agent::ChainOfThoughtAgent.new(llm: :openai, llm_api_key: ENV[OPEN_IA], tools: ['search', 'calculator'])
agent.run(question: "How many full soccer fields would be needed to cover the distance between NYC and DC in a straight line?")
```

```bash
chain_of_thought_agent.rb:53:in `+': no implicit conversion of nil into String (TypeError)
    prompt += response
```

and also when I don't get the error I don't get the message response.

**Comment by andreibondarev** [comment]
You don't actually need to do this explicitly:
```ruby
GoogleSearch.api_key = ENV[KEY_SERAPI]
```

Try setting it either in your terminal with:
```bash
export SERPAPI_API_KEY=...
```
or in the console directly:
```ruby
ENV["SERPAPI_API_KEY"]=...
```
That's the env var that it's looking for: https://github.com/andreibondarev/langchainrb/blob/0.3.14/lib/tool/serp_api.rb#L46

Also -- in order to get a much better logging, can you try setting:
```ruby
Langchain.logger.level = :debug
```

Try again, and let me know if that fixed it for you!

**Comment by pargara** [comment]
to be honest, I'm sending the key for SERAPI as a string `GoogleSearch.api_key = "f6f58..."` for now

and I ended up making it work by placing a `puts`

![Screenshot from 2023-05-30 23-25-23](https://github.com/andreibondarev/langchainrb/assets/48458038/21fbdb82-d816-4b3a-b88b-cfaa0706a949)

**Comment by andreibondarev** [comment]
@pargara I'll close this issue since it seems like it working for you now!
